### ISSUE TITLE
Add a summary PR comment

### ISSUE THREAD

**Issue by mschfh** [Doist/optimize-images-action#4]
Please consider implementing a report comment with a list/summary, similar to this action: https://github.com/marketplace/actions/image-optimizer

https://user-images.githubusercontent.com/129972/73187362-348f0f00-4119-11ea-9c25-cdbadbec66e4.png

**Comment by goncalossilva** [comment]
@mschfh there is an example in the README on how to achieve that. It leads to something like this:

<img width="912" alt="image" src="https://github.com/Doist/optimize-images-action/assets/102931/3f05dd2a-673e-477e-addd-908a75c7088c">

Considering the [minimal size](https://share.getcloudapp.com/p9uZDBlE) (5 lines after this action), I think it would be scope creep to add it as a built-in feature. Composition is a better approach, IMHO.
